# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: [brew-style]
repos:
  - repo: local
    hooks:
      - id: brew-style
        name: brew style --fix
        # To check the installed tap:
        # brew style andreoliwa/formulae
        entry: brew style --fix .
        language: ruby
