# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: brew-style
        name: brew style andreoliwa/formulae
        entry: brew style andreoliwa/formulae --fix
        language: ruby
        types: [ruby]
