# This file was generated by GoReleaser. DO NOT EDIT.
cask "logseq-doctor" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "f0406d2757c9a143fee5023c493bb40afa4bf3829ac5758b81cc986ef737bd2f"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d548423042897c94f45b05a2e74f73422981aa6b332654fe248089742dd9c0d7"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d002ab1b139e36f7664fc1e76ea6683648a642a4f05b0f578fe476e8a8cf829d"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1cb2d386e9a475e5beedcb7d031349155734d6670477b3c0d07207bcce3e2ae3"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "logseq-doctor"
  desc "Heal your Logseq Markdown files"
  homepage "https://github.com/andreoliwa/logseq-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logseq-doctor"

  # No zap stanza required
end
