# This file was generated by GoReleaser. DO NOT EDIT.
cask "logseq-doctor" do
  name "logseq-doctor"
  desc "Heal your Logseq Markdown files"
  homepage "https://github.com/andreoliwa/logseq-doctor"
  version "0.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logseq-doctor"

  on_macos do
    on_intel do
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Darwin_x86_64.tar.gz"
      sha256 "ec418fa4948ff41780fa84c33a4a4ed20dc18d746295a9e217d62fa8b3de097f"
    end
    on_arm do
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Darwin_arm64.tar.gz"
      sha256 "0bc531df8cc15b1c832275d275308014a3ca80ead4ae2c0570ece3e7c6991b47"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Linux_x86_64.tar.gz"
      sha256 "f46b204512779773e11a7d05f10a3e598c8a641cc598ad9dffae7ec26d8ce878"
    end
    on_arm do
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Linux_arm64.tar.gz"
      sha256 "2855dd66366c3450f982aa9e49486fcda7d1f2d3a3d0d64d37a8a1170adc44b9"
    end
  end

  # No zap stanza required
end
