# This file was generated by GoReleaser. DO NOT EDIT.
cask "logseq-doctor" do
  version "0.6.1"

  name "logseq-doctor"
  desc "Heal your Logseq Markdown files"
  homepage "https://github.com/andreoliwa/logseq-doctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lqd"

  on_macos do
    on_intel do
      sha256 "e1e942e7cc134a0b265bddfade383db942e4fdb1f8b71ab2f4c52c8152a83f89"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d3c0d1b9b1ff34a11264248970029dba59e194c6f8e7cea3e8a9b7d9b6aa950f"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79f6ad02e51936868f9802f3a766bd30a636e0435383e67f47e2059445621670"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a50bfcedcc07b49bc4eeb0eb4e67d5c478679e16a1fc5545175d236bc7aba1d5"
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v#{version}/logseq-doctor_#{version}_Linux_arm64.tar.gz"
    end
  end

  # No zap stanza required
end
