# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogseqDoctor < Formula
  desc "Heal your Logseq Markdown files"
  homepage "https://github.com/andreoliwa/logseq-doctor"
  version "0.6.0"
  license "MIT"
  disable! date: "2025-10-19", because: "the cask should be used now instead", replacement_cask: "logseq-doctor"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreoliwa/logseq-doctor/archive/refs/tags/v0.6.1.tar.gz"
      sha256 "5676693fd6ae70bd0fb176b9240d8bc18f72c8c25a1fb1f4ff81122088550539"

      define_method :install do
        bin.install "lqd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v0.6.0/logseq-doctor_0.6.0_Darwin_arm64.tar.gz"
      sha256 "9dce099ffec65cd1f7356aa644e1f0258342b954daca8583978da1676f439c20"

      define_method :install do
        bin.install "lqd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v0.6.0/logseq-doctor_0.6.0_Linux_x86_64.tar.gz"
      sha256 "d6a9c01248da79fcdec4c8b54268ff0fa7e329484b54307bdc0c99ba2973bbc3"
      define_method :install do
        bin.install "lqd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v0.6.0/logseq-doctor_0.6.0_Linux_arm64.tar.gz"
      sha256 "f2661d5b28271867dc81c21b37d771ca09b4bedef4078d6f93d84ed051c5beaf"
      define_method :install do
        bin.install "lqd"
      end
    end
  end

  test do
    assert_match "Logseq Doctor heals your Markdown files for Logseq.", shell_output("#{bin}/lqd")
  end
end
