# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LogseqDoctor < Formula
  desc "Heal your Logseq Markdown files"
  homepage "https://github.com/andreoliwa/logseq-doctor"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v0.4.0/logseq-doctor_Darwin_x86_64.tar.gz"
      sha256 "4d5a06b0c60cfda4f057eef874d48595e7bf6b9bfd700abd8ccc09bf4ca4ab28"

      def install
        bin.install "logseq-doctor" => "lsdg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v0.4.0/logseq-doctor_Darwin_arm64.tar.gz"
      sha256 "eb52b954ce7731b8b6f4c529e4b1c70fb14659688031d3ce4dee97df79185dcb"

      def install
        bin.install "logseq-doctor" => "lsdg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v0.4.0/logseq-doctor_Linux_x86_64.tar.gz"
      sha256 "9c383784ac47a8ffb8e48a46fedd009169fb9b099fe9cb58966bcfa9e3678481"

      def install
        bin.install "logseq-doctor" => "lsdg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreoliwa/logseq-doctor/releases/download/v0.4.0/logseq-doctor_Linux_arm64.tar.gz"
      sha256 "1893dfd8a85c2d709ff61bf0b3d4ff58b1eeac0b84188447b1ebd0f4e471d4a4"

      def install
        bin.install "logseq-doctor" => "lsdg"
      end
    end
  end

  test do
    assert_match "Logseq Doctor (Go) heals your Markdown files for Logseq.", shell_output("#{bin}/lsdg --help")
  end
end
